cygnusb2b/informa-business-intelligence

- packages/lazarus-shared/browser/index.js
- packages/lazarus-shared/browser/load-eloqua-iframes.vue
- packages/lazarus-shared/components/blocks/global-left-rail.marko
- packages/lazarus-shared/components/load-eloqua-iframes.marko
- packages/lazarus-shared/components/marko.json
- packages/lazarus-shared/components/nodes/content-card.marko
- packages/lazarus-shared/components/nodes/content-list.marko
- packages/lazarus-shared/components/nodes/content-page-card.marko
- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/components/nodes/marko.json
- packages/lazarus-shared/graphql/fragments/content-list.js
- packages/lazarus-shared/graphql/fragments/content-page.js
- packages/lazarus-shared/package.json
- packages/lazarus-shared/start-server.js
- packages/lazarus-shared/templates/content/index.marko
- packages/lazarus-shared/theme.scss
- sites/tdworld.com/config/navigation.js
- Remove "TH" from date formats (force for all sites)
- Handle Eloqua iframes in content bodies
- Disable infinite scroll on webinar pages
- Only show Article, MediaGallery and Video in global, left-rail feed
- Fix T&D World webinar and whitepaper links in menu
- Add "Sponsored Content" label to content lists, cards, and content page
> Alpha5 revisions

- packages/informa-gam/components/adunit.marko
- packages/informa-gam/components/inject-adunits.marko
- packages/informa-gam/package.json
- packages/lazarus-shared/package.json
- services/gam/graphql/resolvers/index.js
- services/gam/graphql/utils/adunit-projection.js
- yarn.lock
Some GAM configs have their targeting and breakpoint settings defined at the root of the object instead of under `settings`. The GAM service resolvers now account for this.
- Fixes issue where some ads were showing on larger screen sizes when they shouldn't have
- Handles the `testAd` query parameter and passes the value along to GAM as a targeting key/value
- Upgrades `@base-cms/marko-web-gam` to `1.0.0-rc.14` which now displays the `sizeMapping` property as a data attribute
> Account for root level GAM targeting and breakpoints; add testAd param

- sites/americanmachinist.com/server/routes/dynamic-page.js
- sites/asumag.com/server/routes/dynamic-page.js
- sites/bulktransporter.com/server/routes/dynamic-page.js
- sites/contractingbusiness.com/server/routes/dynamic-page.js
- sites/contractormag.com/server/routes/dynamic-page.js
- sites/ecmweb.com/server/routes/dynamic-page.js
- sites/ehstoday.com/server/routes/dynamic-page.js
- sites/electricalmarketing.com/server/routes/dynamic-page.js
- sites/electronicdesign.com/server/routes/dynamic-page.js
- sites/ewweb.com/server/routes/dynamic-page.js
- sites/fleetowner.com/server/routes/dynamic-page.js
- sites/forgingmagazine.com/server/routes/dynamic-page.js
- sites/foundrymag.com/server/routes/dynamic-page.js
- sites/hpac.com/server/routes/dynamic-page.js
- sites/hydraulicspneumatics.com/server/routes/dynamic-page.js
- sites/industryweek.com/server/routes/dynamic-page.js
- sites/machinedesign.com/server/routes/dynamic-page.js
- sites/mhlnews.com/server/routes/dynamic-page.js
- sites/mwrf.com/server/routes/dynamic-page.js
- sites/newequipment.com/server/routes/dynamic-page.js
- sites/powerelectronics.com/server/routes/dynamic-page.js
- sites/refrigeratedtransporter.com/server/routes/dynamic-page.js
- sites/rermag.com/server/routes/dynamic-page.js
- sites/sourcetoday.com/server/routes/dynamic-page.js
- sites/tdworld.com/server/routes/dynamic-page.js
- sites/trailer-bodybuilders.com/server/routes/dynamic-page.js
- sites/trucker.com/server/routes/dynamic-page.js
- sites/truckfleetmro.com/server/routes/dynamic-page.js
Previously, `/page/foo/bar` would not not match the dynamic page route. This fixes that issue.
> Ensure dynamic page routes support “deep” paths

- packages/informa-gam/utils/can-load-prestitial.js
- packages/lazarus-shared/components/elements/content-body.marko
- packages/lazarus-shared/components/elements/marko.json
- packages/lazarus-shared/components/nodes/content-page-card.marko
- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/components/nodes/marko.json
- packages/lazarus-shared/routes/content.js
- packages/lazarus-shared/templates/content/whitepaper.marko
- packages/lazarus-shared/theme.scss
Can also, (optionally) have ads disabled.
Applied to whitepapers (with ads off).
> Support for full-width content pages

- packages/site-setup/template/config/navigation.js
Newsletter spelling was already corrected for the sites, but the template still had the incorrect spelling.
> newsletter spelling

- services/gam/graphql/utils/clean-path-value.js
The previous regex was not declaring the special chars as a list of replacement options. As such, these characters were not being replaced.
> Ensure additional special chars are replaced

- packages/informa-gam/components/components/prestitial-script.marko
https://southcomm.atlassian.net/browse/CS-3951
=> is preventing opacity removal, which is in turn causing sites not to display on IE11
There are also a number of styling display issues related to the use of flex box in IE11, which would need to be addressed in a different request.
> Replace arrow function with standard function

- packages/lazarus-shared/browser/directory-facets/facet.vue
- packages/lazarus-shared/browser/directory-facets/graphql/directory-sections.js
- packages/lazarus-shared/browser/directory-facets/graphql/root-sections.js
- packages/lazarus-shared/browser/directory-facets/icons/_wrapper.vue
- packages/lazarus-shared/browser/directory-facets/icons/add-circle-outline.vue
- packages/lazarus-shared/browser/directory-facets/icons/filter-none.vue
- packages/lazarus-shared/browser/directory-facets/icons/remove-circle-outline.vue
- packages/lazarus-shared/browser/directory-facets/index.vue
- packages/lazarus-shared/browser/directory-facets/link.vue
- packages/lazarus-shared/browser/directory-facets/list.vue
- packages/lazarus-shared/browser/directory-facets/loading-spinner.vue
- packages/lazarus-shared/browser/directory-facets/node.vue
- packages/lazarus-shared/browser/directory-facets/toggle-button.vue
- packages/lazarus-shared/browser/directory-facets/utils/get-as-array.js
- packages/lazarus-shared/browser/directory-facets/utils/get-as-object.js
- packages/lazarus-shared/browser/directory-facets/utils/get-edge-nodes.js
- packages/lazarus-shared/browser/index.js
- packages/lazarus-shared/components/directory-facets.marko
- packages/lazarus-shared/components/flows/content-load-more.marko
- packages/lazarus-shared/components/marko.json
- packages/lazarus-shared/components/nodes/content-page-card.marko
- packages/lazarus-shared/graphql/fragments/directory-page.js
- packages/lazarus-shared/package.json
- packages/lazarus-shared/routes/website-section.js
- packages/lazarus-shared/scss/_directory-facets.scss
- packages/lazarus-shared/templates/website-section/directory.marko
- packages/lazarus-shared/theme.scss
Enabled by default on all sites under the `/directory` route. If a site doesn't have a `directory` section, the page will simply 404 (as expected).
> Create directory landing page with category tree navigation

- sites/hydraulicspneumatics.com/index.js
- sites/hydraulicspneumatics.com/server/routes/index.js
Loads the directory landing page on `/manufacturer-directory` and `/distributor-directory` for `hydraulicspneumatics.com` only.
> Add custom directory routes

- sites/tdworld.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171114225
- Add /wildfire
- Correct alphabetical ordering of navigation by switching Vegetation Management and Utility Business
Current:
New:
> Add "Wildfire" and "Vegetation Management" to site menu

- packages/informa-gam/components/adunit.marko
- packages/informa-gam/components/prestitial.marko
- packages/informa-gam/middleware.js
Specifically fixes an issue with the `native_inline { pos: nativekey_13_1 }` positions not firing.
> Ensure fluid ad unit sizes are handled globally

- packages/informa-gam/components/direct-inject-adunit.marko
- packages/informa-gam/components/marko.json
- packages/lazarus-shared/components/elements/content-body.marko
- packages/lazarus-shared/components/elements/marko.json
- packages/lazarus-shared/components/flows/content-page-load-more.marko
- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/components/nodes/marko.json
Previously, all additional content page calls to this ad unit was using `nativekey_13_1` for the `pos` value. Now, as each new content page is loaded via infinite scroll, the final number will be incremented by one, up to a max of ten.
- `nativekey_13_1`
- `nativekey_13_2`
- ...
- `nativekey_13_10`
> Increment the `nativekey_13_[n]` inline ads on content pages

- packages/informa-gam/middleware.js
The context values are not being taken into account when the GraphQL client is caching the ad unit results. As such, when two content items are loaded within the same request, the second item will receive the targeting values of the first. This sets the GraphQL fetch policy to `no-cache` to prevent this.
In addition, some (internal) cache keys were being generated with camel and kebab case object properties. This corrects that by camelizing all context keys.
> Disable GraphQL cache when requesting ad units

- packages/lazarus-shared/templates/content/print.marko
Thereby allowing Google Analytics tracking.
> Add GTM to content print pages

- sites/industryweek.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171507360
Remove “Trump and Manufacturing” from the hamburger menu.
Add "IndustryWeek at 50" to the hamburger menu (same location as Trump section)
> Replace Trump and Manufacturing navigation item with IndustryWeek at 50 

- sites/electronicdesign.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171508263
> Remove Design Learning Center from hamburger nav

- sites/fleetowner.com/config/navigation.js
- sites/trucker.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171867587
Added /covid-19-coverage links to the navs for Trucker and Fleetowner
> Add COVID-19 to menu navigation

- packages/lazarus-shared/newrelic.js
Split out app_name in Newrelic to help get more granular data. It also makes it match the rest of the repos structure.
> Updated Newrelic app_name to match repo name

- sites/americanmachinist.com/config/navigation.js
- sites/ehstoday.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172213040
**From request:** 
The event marketing manager for the Manufacturing sites would like to showcase these 2 events via hamburger navigation links:
Manufacturing & Technology (https://www.mfgtechshow.com)
Safety Leadership Conference ( https://www.safetyleadershipconference.com​ )
This hamburger nav update would be for the following sites:
IndustryWeek
NED
MH&L
Machine Design
American Machinist
EHS Today
So above the "Magazine Subscription" link across the hamburger navs on the Manufacturing sites, we would add a link for "Manufacturing & Technology" and "Safety Leadership Conference" (and have them link off to the URLs listed above).
> Add event links to secondary navs

- sites/ehstoday.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172314282
New:
> Add Covid 19 link to secondary nav

- packages/lazarus-shared/components/elements/content-body.marko
- packages/lazarus-shared/components/elements/content-comments.marko
- packages/lazarus-shared/components/elements/marko.json
- packages/lazarus-shared/identity-x.js
- packages/lazarus-shared/routes/index.js
- packages/lazarus-shared/scss/_identity-x.scss
- packages/lazarus-shared/start-server.js
- packages/lazarus-shared/theme.scss
- sites/industryweek.com/config/site.js
Currently, comments are only enabled for Industry Week.
The IdentityX middleware was moved into the `onStart` hook to ensure service availability in load more calls. This is required since the IBI sites utilize content-to-content scroll.
> Add support for comments

- packages/informa-gam/package.json
- packages/lazarus-shared/components/document.marko
- packages/lazarus-shared/package.json
- sites/electronicdesign.com/config/site.js
- yarn.lock
Add support for lazy loading of ads. This is disabled by default and can be enabled/configured within each site config. An example configuration (though disabled) was added to Electronic Design.
See `sites/electronicdesign.com/config/site.js` for a configuration example.
> GAM lazy loading

- sites/mwrf.com/config/navigation.js
https://www.pivotaltracker.com/story/show/173562845
- Removed the "Experts" link in the hamburger nav.
- Renamed the Resources hamburger menu item "MWRF Resources" and moved it to the top of the menu
Current:
New:
> Update Resources menu items

- sites/ehstoday.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
enabled: true, // set to true to enable lazy loading
fetchMarginPercent: 100, // fetch ad when one viewport away
renderMarginPercent: 50, // render ad when half viewport away
mobileScaling: 2, // double these on mobile
> Enable Lazy Load Ads

- sites/americanmachinist.com/config/leaders.js
- sites/americanmachinist.com/config/site.js
- sites/americanmachinist.com/server/styles/index.scss
https://www.pivotaltracker.com/story/show/173992767
Note: Had to manually set the logo background color due to a variable override issue in informa leaders, will do a follow-up to investigate the issue further
> Setup /leaders for AM

- packages/lazarus-shared/components/blocks/home-page-hero-with-recommended.marko
- packages/lazarus-shared/components/page-wrappers/website-section/default.marko
- packages/lazarus-shared/theme.scss
- update homepage list to pull hero feed and standard list flow with no teaser.
- Adjust css accordingly
> Update layout of recommended block & adjust css accordingly 

- packages/lazarus-shared/browser/auto-scroll.vue
- packages/lazarus-shared/browser/directory-facets/list.vue
- packages/lazarus-shared/browser/index.js
- packages/lazarus-shared/scss/_directory-facets.scss
- packages/lazarus-shared/templates/website-section/directory.marko
- packages/lazarus-shared/theme.scss
[**DEV-22**](https://southcomm.atlassian.net/browse/DEV-22)
- update left col to have scrollable, non-sticky, categories followed by a 300x250 ad
- update right col to have ability for featured companies(limit of 3) and then a list of latest companies(7)
- after main portion of page it will scrollin to more companies full with
— every load more page will have an 970/728 followed by 18 companies.
> Port EBM directory layout to Informa sites

- packages/lazarus-shared/components/blocks/home-page-hero-with-recommended.marko
- packages/lazarus-shared/templates/index.marko
- packages/lazarus-shared/theme.scss
add css to use flex grow when right col-md-4 is empty on the homepage
> Add css to account for empty recommended block

- packages/lazarus-shared/templates/magazine/issue.marko
https://southcomm.atlassian.net/browse/DEV-144
On the live site, the load more content was not displaying.
New:
> Corrected load-more config for magazine issue page

- packages/lazarus-shared/theme.scss
This PR needs to be released in conjunction with the /base-cms PR: https://github.com/base-cms/base-cms/pull/480
https://southcomm.atlassian.net/browse/DEV-157
Allow the left column to display on mobile sizes without the sticky elements.
Left column displays below the right column on mobile sizes.
Note: The header and footer display issues are pre-existing concerns with Electronic Design.
New Mobile:
New Tablet:
> Lazarus Theme Updates

- packages/lazarus-shared/theme.scss
Footers were exceeding screen limits on mobile (header fix coming in separate PR)
Current:
New:
> Correct mobile layout of footer

- packages/lazarus-shared/templates/content/index.marko
- packages/lazarus-shared/templates/index.marko
- packages/lazarus-shared/templates/website-section/index.marko
- packages/lazarus-shared/templates/website-section/leaders.marko
Move the @below-contain hidden ad call to the @above-container call to prevent the lazyload delay from delaying the out of page || hidden ads from being fired correctly.
> Move hidden ad call to @above contain fix lazyload

- packages/lazarus-shared/browser/load-eloqua-iframes.vue
Sales started adding tracking codes in mailed links to certain Whitepapers which are gated by eloqua forms.  Since those are iframe embeds, the qs needs to be maintained to get the value into the form itself.
> add passthrough of querystring from website url to eloqua iframe

- packages/lazarus-shared/components/page-wrappers/website-section/default.marko
The ad team is continuously accidentally targeting this position in GAM, causing confusion among the groups.  I dug around GAM and it doesn’t look like anyone’s actually using this position (correctly) so it’s being commented out until/if they want it.
-----
> Remove `native_article_4` gam position from section pages

- packages/lazarus-shared/templates/content/index.marko
https://southcomm.atlassian.net/browse/DEV-244
Exclude banner ads on Electronic Design's promotion content type.
New:
Current:
> Exclude banner ads on ED promotion content type

- sites/electronicdesign.com/config/site.js
- sites/mwrf.com/config/site.js
https://southcomm.atlassian.net/browse/DEV-286
- Swap the "Products and Solutions" & "Industry Insights" content blocks around
- Replace the "Defense" content block with "Technology Advancements" (https://www.mwrf.com/resources/technology-advancements)
- Replace the  "Components" content block with "Industry Insights" (https://www.mwrf.com/resources/industry-insights)
- Replace the "Systems" content block with"Products and Solutions" (https://www.mwrf.com/resources/products-and-solutions)
> Homepage block rearrangements 

- sites/asumag.com/config/navigation.js
- sites/contractingbusiness.com/config/navigation.js
- sites/electricalmarketing.com/config/navigation.js
- sites/electronicdesign.com/config/navigation.js
- sites/hydraulicspneumatics.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
- sites/sourcetoday.com/config/navigation.js
- sites/trucker.com/config/navigation.js
Did a find in all `sites` for `http:` and updated them to `https:` (I double-checked each URL before updating to make sure they were all actually secure).  Found one that didn't work at all, so I removed it ("Advertise" on electricalmarketing.com).
Also updated some nav links in HPN and MD per https://southcomm.atlassian.net/browse/DEV-298
(Copied from the ticket):
• Replace “Directories” with “H&P Connect”, and point it to https://www.hydraulicspneumatics.com/hpconnect
• Replace “Experts” with “Digital Edition Archives” and point it to https://www.hydraulicspneumatics.com/magazine/5e6baaf6a1b8b3c9814869e5
• Lower in the menu, re-point “Manufacturer’s Directory” to https://www.hydraulicspneumatics.com/hpconnect
• Above the CSIA Exchange listing (at the top of the lower part of the menu) …
> Various navigation updates

- packages/leaders/scss/index-page.scss
- sites/hydraulicspneumatics.com/config/leaders.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/hydraulicspneumatics.com/server/styles/index.scss
Add Leaders to H&P's /hpconnect page: https://www.hydraulicspneumatics.com/hpconnect
Updated logo background color: 
Also equalized the margin around the header.  Above image is post-change, here's what it looks like on prod (with default background color):
> Enable Leaders on H&P

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/ehstoday.com/config/site.js
- sites/electricalmarketing.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/tdworld.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
Note: TDWorld and RERMag already had it enabled
https://southcomm.atlassian.net/browse/DEV-308
American Machinist example (with inquiry temporarily enabled for this company)
> Enable inquiry on all Informa sites

- packages/lazarus-shared/routes/index.js
- sites/fleetmaintenance.com/config/site.js
Check for `removeSubscribeRoute` in the site config, which allows a site-specific way to override the /subscribe route in `./lazarus-shared/routes/index.js`.  Kinda hacky, I know.  If we weren’t moving off this platform in the next few months I would do something cleaner, but FM wants a custom subscribe page, and we can’t redirect /subscribe while there’s an active route in `routes/index.js`
With `removeSubscribeRoute = true` in site.config:
Without `removeSubscribeRoute` in site.config (or set to false):
> Override /subscribe route

- packages/lazarus-shared/components/elements/marko.json
- packages/lazarus-shared/components/elements/metatags.marko
- packages/lazarus-shared/templates/content/index.marko
https://southcomm.atlassian.net/browse/DEV-393
Still need to figure out how to add the website schedule section names, but the rest is working:
> Add meta tags for Eloqua behavioral tracking

- packages/lazarus-shared/scss/_company-page.scss
- packages/lazarus-shared/theme.scss
Per https://southcomm.atlassian.net/browse/DEV-386
- Removed css preventing alignment
- Also fixed a mobile issue noticed during testing
Current:
Note -- text is hugging the right side of the container, a longer word would cause an overflow
Current desktop embed not aligning per WYSIWYG setting of "right"
Alignment on mobile and tablet will stay the same as current:
New:
On small phones...
Will look the same as before on larger phones...
New embed alignment on desktop sizes:
> Image embeds alignment correction

- sites/newequipment.com/config/site.js
Per https://southcomm.atlassian.net/browse/DEV-438, they want the /subscribe page to route to an external form rather than a landing page.
> Add route override for /subscribe page

- packages/lazarus-shared/templates/content/company.marko
- packages/lazarus-shared/templates/content/full-width.marko
Already included in the default content template, now being pushed to remaining template override files.  Relates to: https://github.com/cygnusb2b/informa-business-intelligence/pull/247
Whitepaper using the "Full Width" template override used for testing: https://www.electronicdesign.com/power-management/whitepaper/21152694/cressall-resistors-resistance-beyond-the-four-walls
Now-included meta tags on that whitepaper:
Company using the "Company" template override used for testing: https://www.electronicdesign.com/companies/company/21153103/sitime
Now-included (albeit sparse) meta tags on that Company:
> Include metatags in Company & “full-width” content overrides

- packages/lazarus-shared/components/blocks/company-page-load-more.marko
To skip the 6 article query param limit set in packages/lazarus-shared/components/blocks/company-content-list.marko
Per https://southcomm.atlassian.net/browse/DEV-124
New:
Current:
> Added skip to company page load more

- packages/lazarus-shared/identity-x.js
- packages/lazarus-shared/package.json
- yarn.lock
Makes `regionCode` and `countryCode` required when a new/unverified user logs in using IdentityX. If a country is selected that also has an enabled regional consent question, that question will also be prompted. This is the website implementation of base-cms/base-cms#509 and, as such, required an upgrade of the `@base-cms/marko-web-identity-x` package
> Require `regionCode` and `countryCode` on IdentityX login

- packages/lazarus-shared/components/blocks/magazine-publications.marko
- packages/lazarus-shared/scss/_magazine.scss
- Corrected “queryFragmet” to “queryFragment”
- Added margin-top setting so buttons would display on /magazine pages, instead of hiding behind the magazine image
Current:
New:
> Bug fix for /magazines buttons

- packages/lazarus-shared/components/nodes/content-card.marko
- packages/lazarus-shared/components/nodes/content-list.marko
- packages/lazarus-shared/components/nodes/content-page-card.marko
- packages/lazarus-shared/components/nodes/marko.json
- packages/lazarus-shared/templates/content/print.marko
Per https://southcomm.atlassian.net/browse/DEV-542
Added "Members Only Content" header to items with "Members Only" label, and "Leaders Content" header to items with "Leaders" label., using the same settings as items using the "Sponsored Content" header for "Sponsored" label.
Examples with content from https://manage.electronicdesign.com/content/edit/whitepaper/21154985 / https://www.electronicdesign.com/members / http://0.0.0.0:5718/members/ebook-library/whitepaper/21154985/bob-pease-ebook-vol-2-download
Had to temporarily add the "Leaders" label to the preview content below, because I couldn't find an article on the sites I checked with a Leaders label.
> Add “Members Only” header to content with label

- packages/lazarus-shared/components/elements/content-body.marko
These injections use javascript targeting and run serially, so they are sometimes counting the previously injected code in the character count, which puts some of them very close to each other.
> Changing character inject targets due to bug
