- sites/americanmachinist/server/styles/index.scss
- sites/asumag/server/styles/index.scss
- sites/bulktransporter/server/styles/index.scss
- sites/contractingbusiness/server/styles/index.scss
- sites/contractormag/server/styles/index.scss
- sites/ecmweb/server/styles/index.scss
- sites/ehstoday/server/styles/index.scss
- sites/electricalmarketing/server/styles/index.scss
- sites/electronicdesign/server/styles/index.scss
- sites/ewweb/server/styles/index.scss
- sites/fleetowner/server/styles/index.scss
- sites/forgingmagazine/server/styles/index.scss
- sites/foundrymag/server/styles/index.scss
- sites/hpac/server/styles/index.scss
- sites/hydraulicspneumatics/server/styles/index.scss
- sites/machinedesign/server/styles/index.scss
- sites/mhlnews/server/styles/index.scss
- sites/mwrf/server/styles/index.scss
- sites/newequipment/server/styles/index.scss
- sites/powerelectronics/server/styles/index.scss
- sites/refrigeratedtransporter/server/styles/index.scss
- sites/rermag/server/styles/index.scss
- sites/sourcetoday/server/styles/index.scss
- sites/trailer-bodybuilders/server/styles/index.scss
- sites/trucker/server/styles/index.scss
- sites/truckfleetmro/server/styles/index.scss
For remaining 26 sites (industryweek and tdworld were already set).
> Set SASS color variables

- packages/lazarus-shared/components/blocks/global-left-rail.marko
- packages/lazarus-shared/components/flows/content-hero.marko
- packages/lazarus-shared/components/flows/marko.json
- packages/lazarus-shared/templates/content/index.marko
- packages/lazarus-shared/templates/index.marko
- packages/lazarus-shared/theme.scss
- services/gam/dataloaders/content.js
- services/gam/graphql/resolvers/index.js
- services/gam/graphql/utils/resolve-tokens.js
- Properly handle "program" ad positions
- Increate padding for global left rail and page columns
- Add bottom leaderboard ad position to homepage
> Alpha4 revisions

- packages/informa-gam/components/prestitial.marko
- packages/informa-gam/utils/can-load-prestitial.js
- packages/lazarus-shared/components/document.marko
- sites/asumag.com/config/site.js
- sites/asumag.com/server/public/robots.txt
- sites/contractingbusiness.com/server/public/robots.txt
- sites/contractormag.com/config/site.js
- sites/contractormag.com/server/public/robots.txt
- sites/ecmweb.com/server/public/robots.txt
- sites/electricalmarketing.com/server/public/robots.txt
- sites/ewweb.com/server/public/robots.txt
- sites/hpac.com/server/public/robots.txt
- sites/rermag.com/server/public/robots.txt
- sites/tdworld.com/server/public/robots.txt
- Fix Business and Finance section on asumag
- Ensure wrapper opacity only set when prestitial can load
- Remove disallow all for 12/6 site launches
- Use correct website section on homepage on contractingbusiness
> Alpha9 revisions

- services/gam/graphql/utils/clean-path-value.js
Ensures that multiple underscores are properly removed.
> Replace multiple underscores are replaced last

- packages/lazarus-shared/theme.scss
> Ensure embedded Eloqua forms clear surrounding content

- sites/americanmachinist.com/server/public/robots.txt
- sites/bulktransporter.com/server/public/robots.txt
- sites/ehstoday.com/server/public/robots.txt
- sites/electronicdesign.com/server/public/robots.txt
- sites/fleetowner.com/server/public/robots.txt
- sites/forgingmagazine.com/server/public/robots.txt
- sites/foundrymag.com/server/public/robots.txt
- sites/hydraulicspneumatics.com/server/public/robots.txt
- sites/industryweek.com/server/public/robots.txt
- sites/machinedesign.com/server/public/robots.txt
- sites/mhlnews.com/server/public/robots.txt
- sites/mwrf.com/server/public/robots.txt
- sites/newequipment.com/server/public/robots.txt
- sites/powerelectronics.com/server/public/robots.txt
- sites/refrigeratedtransporter.com/server/public/robots.txt
- sites/sourcetoday.com/server/public/robots.txt
- sites/trailer-bodybuilders.com/server/public/robots.txt
- sites/trucker.com/server/public/robots.txt
- sites/truckfleetmro.com/server/public/robots.txt
> Remove disallow all from robots.txt

- packages/lazarus-shared/browser/index.js
- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/package.json
- packages/lazarus-shared/theme.scss
- yarn.lock
> Add social sharing

- packages/lazarus-shared/templates/index.marko
- packages/lazarus-shared/theme.scss
- sites/industryweek.com/config/site.js
> Add (optional) program sections to homepage

- sites/industryweek.com/config/navigation.js
https://southcomm.atlassian.net/browse/CS-3754
> CS3754-IW: removed Cloud Manufactoring from nav

- sites/mhlnews.com/config/navigation.js
https://southcomm.atlassian.net/browse/CS-3937
> CS3937-MHL: remove magazine link from nav

- sites/tdworld.com/config/navigation.js
> Remove Apps & Calculators from drop down menu

- sites/americanmachinist.com/config/navigation.js
> Remove Calculators from site menu

- sites/newequipment.com/config/dragon-forms.js
https://southcomm.atlassian.net/browse/CS-4127
> Set newsletter dragonform config

- packages/lazarus-shared/components/elements/content-body.marko
> Add download button to whitepaper pages

- sites/electronicdesign.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171131142
> Update "Contribute" link in site menu

- packages/lazarus-shared/package.json
- yarn.lock
Adds latest IdentityX package that supports region and postal codes.
> Upgrade @base-cms dependencies to 1.19.0

- packages/lazarus-shared/routes/dynamic-page.js
Previously it would only match alpha numerical characters and -
> Change page alias lookup to support all characters

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/ehstoday.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
Reverts base-cms-websites/informa-business-intelligence#76
> Revert "Enable IdentityX for all informa sites"

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/ehstoday.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
Double revert of base-cms-websites/informa-business-intelligence#76 and base-cms-websites/informa-business-intelligence#91
> Enable IdentityX for all Informa sites

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/ehstoday.com/config/site.js
- sites/electricalmarketing.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/tdworld.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
> Allow GAM Account ID To Be overwritten By ENV

- packages/lazarus-shared/components/blocks/global-left-rail.marko
New - "Test" whitepaper/webinar pulled in
Current:
> Add whitepaper and webinar type to recent rail

- sites/industryweek.com/config/navigation.js
https://www.pivotaltracker.com/story/show/171671547
> Amended navigation url for IndustryWeek at 50

- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/components/nodes/marko.json
- packages/lazarus-shared/components/page-wrappers/content/default.marko
- packages/lazarus-shared/components/page-wrappers/content/marko.json
- packages/lazarus-shared/components/page-wrappers/content/program.marko
- packages/lazarus-shared/components/page-wrappers/marko.json
- packages/lazarus-shared/graphql/fragments/content-page.js
- packages/lazarus-shared/templates/content/index.marko
- packages/lazarus-shared/theme.scss
Ref [PT #171156088 "Create "Custom Channel" template"](https://www.pivotaltracker.com/story/show/171156088)
Adds the custom layout for content pages
> Program content layout

- packages/lazarus-shared/components/gating/content-gate.marko
- packages/lazarus-shared/components/nodes/content-page.marko
- packages/lazarus-shared/graphql/fragments/content-page.js
- sites/electricalmarketing.com/config/site.js
> Electrical marketing gating

- sites/fleetowner.com/config/dragon-forms.js
https://www.pivotaltracker.com/story/show/171898776
> Update newsletter dragonform config

- sites/electronicdesign.com/config/navigation.js
> Update Resource navigation link

- sites/americanmachinist.com/config/navigation.js
- sites/asumag.com/config/navigation.js
- sites/bulktransporter.com/config/navigation.js
- sites/contractingbusiness.com/config/navigation.js
- sites/contractormag.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
- sites/ehstoday.com/config/navigation.js
- sites/electronicdesign.com/config/navigation.js
- sites/ewweb.com/config/navigation.js
- sites/fleetowner.com/config/navigation.js
- sites/forgingmagazine.com/config/navigation.js
- sites/foundrymag.com/config/navigation.js
- sites/hpac.com/config/navigation.js
- sites/hydraulicspneumatics.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
- sites/mwrf.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
- sites/powerelectronics.com/config/navigation.js
- sites/refrigeratedtransporter.com/config/navigation.js
- sites/rermag.com/config/navigation.js
- sites/sourcetoday.com/config/navigation.js
- sites/tdworld.com/config/navigation.js
- sites/trailer-bodybuilders.com/config/navigation.js
- sites/trucker.com/config/navigation.js
- sites/truckfleetmro.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172091396
> Updated advertise links in legacy informa sites

- sites/mwrf.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172232358
> Update Resources link to /page/resources

- sites/industryweek.com/config/navigation.js
- sites/industryweek.com/config/site.js
https://www.pivotaltracker.com/story/show/172211942
> Update homepage block and nav for covid-19

- sites/electricalmarketing.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172271280
* Update digital issue link
* Remove market links
Current:
New:
> Update menu navigation links

- sites/ehstoday.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172314282
> Moved new link to the top of the menus on MHL, EHS

- sites/americanmachinist.com/config/navigation.js
- sites/asumag.com/config/navigation.js
- sites/bulktransporter.com/config/navigation.js
- sites/contractingbusiness.com/config/navigation.js
- sites/contractormag.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
- sites/ehstoday.com/config/navigation.js
- sites/electricalmarketing.com/config/navigation.js
- sites/electronicdesign.com/config/navigation.js
- sites/ewweb.com/config/navigation.js
- sites/fleetowner.com/config/navigation.js
- sites/forgingmagazine.com/config/navigation.js
- sites/foundrymag.com/config/navigation.js
- sites/hpac.com/config/navigation.js
- sites/hydraulicspneumatics.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
- sites/mwrf.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
- sites/powerelectronics.com/config/navigation.js
- sites/refrigeratedtransporter.com/config/navigation.js
- sites/rermag.com/config/navigation.js
- sites/sourcetoday.com/config/navigation.js
- sites/tdworld.com/config/navigation.js
- sites/trailer-bodybuilders.com/config/navigation.js
- sites/trucker.com/config/navigation.js
- sites/truckfleetmro.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172386546 
correction on previous PR
> Update hamburger nav dragon forms reference

- sites/asumag.com/config/navigation.js
- sites/contractingbusiness.com/config/navigation.js
- sites/contractormag.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
- sites/electricalmarketing.com/config/navigation.js
- sites/ewweb.com/config/navigation.js
- sites/hpac.com/config/navigation.js
- sites/rermag.com/config/navigation.js
- sites/tdworld.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172482157
> Remove ‘Ad Choices’ links from navs

- sites/fleetowner.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172682508
> Update advertise link

- sites/refrigeratedtransporter.com/config/dragon-forms.js
https://www.pivotaltracker.com/story/show/172682576
Current:
New:
> Add magazine signup Dragon Form

- sites/fleetowner.com/config/navigation.js
> Add IdeaXchange and update FleetOwner Magazine in site menu

- sites/americanmachinist.com/config/navigation.js
- sites/ehstoday.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172862161
> Update 'Manufacturing & Technology' to 'Manufacturing & Technology Event'

- sites/tdworld.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172969557
> Comment out BG nav item until reskin is updated

- sites/ewweb.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172921314
> Add Podcasts to secondary nav

- packages/lazarus-shared/components.js
- packages/lazarus-shared/components/blocks/magazine-latest-issue.marko
- packages/lazarus-shared/components/blocks/magazine-publications.marko
- packages/lazarus-shared/components/blocks/marko.json
- packages/lazarus-shared/components/flows/magazine-issue-archive.marko
- packages/lazarus-shared/components/flows/magazine-latest-issue.marko
- packages/lazarus-shared/components/flows/marko.json
- packages/lazarus-shared/components/nodes/magazine-issue-archive.marko
- packages/lazarus-shared/components/nodes/magazine-latest-issue.marko
- packages/lazarus-shared/components/nodes/marko.json
- packages/lazarus-shared/fragments.js
- packages/lazarus-shared/graphql/fragments/magazine-issue-archive.js
- packages/lazarus-shared/graphql/fragments/magazine-issue-page.js
- packages/lazarus-shared/graphql/fragments/magazine-latest-issue.js
- packages/lazarus-shared/graphql/fragments/magazine-publication-list.js
- packages/lazarus-shared/graphql/fragments/magazine-publication-page.js
- packages/lazarus-shared/routes/index.js
- packages/lazarus-shared/routes/magazine.js
- packages/lazarus-shared/templates/magazine/index.marko
- packages/lazarus-shared/templates/magazine/issue.marko
- packages/lazarus-shared/templates/magazine/publication.marko
- sites/contractormag.com/config/navigation.js
- sites/contractormag.com/config/site.js
Setup tested on Contractor Mag
> Setup /magazines

- sites/ewweb.com/config/navigation.js
https://www.pivotaltracker.com/story/show/172848729
Current:
New:
> Add whitepapers to nav

- sites/tdworld.com/config/site.js
> Set magazine description for TDW

- packages/lazarus-shared/templates/magazine/publication.marko
https://www.pivotaltracker.com/story/show/172410505
Now the publication page will load more publications:
> Set correct component name for issue archive

- sites/electricalmarketing.com/config/dragon-forms.js
- Removed the extra “n” in the path
https://www.pivotaltracker.com/story/show/173450578
> Fixed newsletter dragon form

- sites/fleetowner.com/config/navigation.js
https://www.pivotaltracker.com/story/show/173542814
> Update advertise footer link

- sites/rermag.com/config/site.js
https://www.pivotaltracker.com/story/show/173612933
> Add LinkedIn to site footer

- sites/ewweb.com/config/navigation.js
https://www.pivotaltracker.com/story/show/173942123
> Update nav link for digital mag of EWW

- sites/ehstoday.com/config/navigation.js
- sites/electronicdesign.com/config/navigation.js
- sites/forgingmagazine.com/config/navigation.js
- sites/foundrymag.com/config/navigation.js
- sites/hydraulicspneumatics.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
- sites/mhlnews.com/config/navigation.js
- sites/mwrf.com/config/navigation.js
- sites/newequipment.com/config/navigation.js
- sites/powerelectronics.com/config/navigation.js
- sites/sourcetoday.com/config/navigation.js
https://www.pivotaltracker.com/story/show/173910819
-- waiting on confirmation from Alex regarding powerelectronics.com update
> Removed ‘Content Licensing’ links from nav lists

- sites/machinedesign.com/config/navigation.js
https://www.pivotaltracker.com/story/show/173983183
> Update MD ham nav menu

- packages/lazarus-shared/scss/_magazine.scss
- packages/lazarus-shared/templates/magazine/index.marko
- packages/lazarus-shared/templates/magazine/issue.marko
- packages/lazarus-shared/templates/magazine/publication.marko
- packages/lazarus-shared/theme.scss
https://www.pivotaltracker.com/story/show/173989695
> Style updates to magazine pages on informa sites

- sites/rermag.com/config/site.js
- sites/tdworld.com/config/site.js
enabled directMail for tdworld and rermag, updated notification email subject lines
> enabled RMI for tdworld, updated configuration for rermag

- sites/electronicdesign.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-112?atlOrigin=eyJpIjoiYTcyN2NkOTczODk3NDcxNDk4YjlhYTY2NTQ3YzY2NjciLCJwIjoiaiJ9
> Correct /advertise link in hamburger nav

- sites/contractormag.com/config/navigation.js
Per Alex via https://southcomm.atlassian.net/browse/DEV-141
> Update ‘Back Issues’ link in site menu

- sites/rermag.com/config/leaders.js
- sites/rermag.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-57?atlOrigin=eyJpIjoiYjQ3YTc2MjNjZDYzNDgyNzlmZDIyODQ3YzlhNTM5ZGEiLCJwIjoiaiJ9
**Note: Requested release date is Sept 1st. The PR is in draft status to prevent release before this date. The code is complete, so it can be reviewed at any time and merged the week of 8/31/20.**
> Turn on leaders for RER and update nav (For release on 9/01/20)

- sites/hydraulicspneumatics.com/config/site.js
- sites/machinedesign.com/config/site.js
https://southcomm.atlassian.net/browse/DEV-158
> Update social media links

- packages/lazarus-shared/templates/index.marko
- sites/industryweek.com/config/site.js
remove configuration and add it by default.
> Enable home page `Recommend` block.

- packages/lazarus-shared/browser/algolia/site-search.vue
- packages/lazarus-shared/package.json
- yarn.lock
> Port algolia sort & date update from ebm theme

- sites/electronicdesign.com/config/site.js
https://southcomm.atlassian.net/browse/DEV-211
> Enable lazy loading for ED

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/electricalmarketing.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/tdworld.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
https://southcomm.atlassian.net/browse/DEV-12
gam: {
...
lazyLoad: {
enabled: true, // set to true to enable lazy loading
fetchMarginPercent: 100, // fetch ad when one viewport away
renderMarginPercent: 50, // render ad when half viewport away
mobileScaling: 2, // double these on mobile
},
},
> Enabled lazyload config for all sites

- packages/lazarus-shared/components/company-page/featured-videos.marko
only display if Featured Video block and title if videos array has something in it
[**DEV-224**](https://southcomm.atlassian.net/browse/DEV-224)
> fix featured video block on all sites

- sites/electronicdesign.com/config/site.js
[**DEV-226**](https://southcomm.atlassian.net/browse/DEV-226)
> Update homepage sections

- sites/rermag.com/config/navigation.js
[**DEV-229**](https://southcomm.atlassian.net/browse/DEV-229)
> update Jobs to Job Listings

- packages/lazarus-shared/theme.scss
[**DEV-230**](https://southcomm.atlassian.net/browse/DEV-230)
> Fix recommended flow height css

- sites/hpac.com/config/navigation.js
[**DEV-199**](https://southcomm.atlassian.net/browse/DEV-199)
> Update digital edition link in menu

- packages/lazarus-shared/scss/_magazine.scss
- packages/lazarus-shared/templates/magazine/index.marko
[**DEV-232**](https://southcomm.atlassian.net/browse/DEV-232)
> Fix magazine landing page layout

- sites/electronicdesign.com/config/site.js
- sites/mwrf.com/config/site.js
> Disable lazyload config on ED and MWRF

- packages/lazarus-shared/scss/components/_page-with-rail.scss
- packages/lazarus-shared/templates/index.marko
- Added page-with-rail settings to index page
> Layout Revisions

- sites/ewweb.com/config/navigation.js
> Update “Market” to “Marketing” in secondary nav

- packages/lazarus-shared/browser/algolia/site-search.vue
> fix logo image display

- sites/asumag.com/config/navigation.js
- sites/contractingbusiness.com/config/navigation.js
- sites/contractormag.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-292
> Update digital edition links in navigation.js

- sites/forgingmagazine.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-327
> Update forging magazine nav menu

- sites/americanmachinist.com/config/site.js
- sites/asumag.com/config/site.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/site.js
- sites/contractormag.com/config/site.js
- sites/ecmweb.com/config/site.js
- sites/ehstoday.com/config/site.js
- sites/electricalmarketing.com/config/site.js
- sites/electronicdesign.com/config/site.js
- sites/ewweb.com/config/site.js
- sites/fleetowner.com/config/site.js
- sites/forgingmagazine.com/config/site.js
- sites/foundrymag.com/config/site.js
- sites/hpac.com/config/site.js
- sites/hydraulicspneumatics.com/config/site.js
- sites/industryweek.com/config/site.js
- sites/machinedesign.com/config/site.js
- sites/mhlnews.com/config/site.js
- sites/mwrf.com/config/site.js
- sites/newequipment.com/config/site.js
- sites/powerelectronics.com/config/site.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/rermag.com/config/site.js
- sites/sourcetoday.com/config/site.js
- sites/tdworld.com/config/site.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/site.js
- sites/truckfleetmro.com/config/site.js
Add public key for search with the following
```javascript
{
filters: status: 1,
filters: ‘NOT type:contact AND NOT type:promotion’,
}
```
> Update algolia searchApiKey

- packages/lazarus-shared/templates/website-section/leaders.marko
- sites/hydraulicspneumatics.com/config/leaders.js
- sites/hydraulicspneumatics.com/server/styles/index.scss
> Leaders title and description changes DEV-351

- packages/lazarus-shared/components/blocks/global-left-rail.marko
This fixes the random sticky ad from the left rail when scrolling within it.
[**DEV-362**](https://southcomm.atlassian.net/browse/DEV-362)
> Remove sticky from ad included within left rail.

- sites/fleetmaintenance.com/config/dragon-forms.js
https://southcomm.atlassian.net/browse/DEV-383
> Update Fleet Maintenance newsletter signup alias

- sites/tdworld.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-384
> Add “Buyer’s Guide” to TDWorld’s menu

- sites/electronicdesign.com/config/navigation.js
- Modify “About Us” URL in site menu & footer
- Rename “Resources” to “Read me First” in site menu
https://southcomm.atlassian.net/browse/DEV-407
> Navigation updates

- sites/trucker.com/config/navigation.js
Per https://southcomm.atlassian.net/browse/DEV-427
> Remove two items from Trucker nav

- sites/ehstoday.com/config/navigation.js
- sites/tdworld.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-485
> Add menu items to TDWorld & EHS

- sites/ecmweb.com/config/navigation.js
- sites/electronicdesign.com/config/navigation.js
- sites/fleetowner.com/config/navigation.js
- sites/hpac.com/config/navigation.js
- sites/industryweek.com/config/navigation.js
- sites/machinedesign.com/config/navigation.js
Relates to: https://southcomm.atlassian.net/browse/DEV-495
> Site menu updates

- sites/fleetmaintenance.com/server/styles/index.scss
- sites/fleetowner.com/server/styles/index.scss
- sites/trailer-bodybuilders.com/server/styles/index.scss
- sites/trucker.com/server/styles/index.scss
https://southcomm.atlassian.net/browse/DEV-430
Update the primary color variable to: 
- Fleet Maintenance: #D71920
- Fleet Owner: #CF202E
- Trailer Body Builder: #ED1C24
- American Trucker: #85332D
"1269" alt="Screen Shot 2021-02-10 at 12 55 18 PM" src="https://user-images.githubusercontent.com/6343242/107550630-45cd8100-6b9f-11eb-8e9e-e18d42465018.png">
> Color updates for commercial vehicle group (CVG)

- sites/tdworld.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-486
Add link to external events site
> Nav update for TD World

- sites/contractormag.com/config/navigation.js
Per https://southcomm.atlassian.net/browse/DEV-535
> Update path for NATE mag on ContractorMag.com

- sites/electronicdesign.com/config/navigation.js
- sites/mwrf.com/config/navigation.js
Per https://southcomm.atlassian.net/browse/DEV-555
> Add ‘Top Stories’ link to ED and MWRF

- sites/machinedesign.com/config/leaders.js
- sites/machinedesign.com/config/site.js
Per https://southcomm.atlassian.net/browse/DEV-549
> Setup Leaders config for MachineDesign

- sites/machinedesign.com/config/leaders.js
Per comment on https://southcomm.atlassian.net/browse/DEV-549
> Update title and description for MD leaders

- sites/mwrf.com/config/leaders.js
- sites/mwrf.com/config/site.js
Per: https://southcomm.atlassian.net/browse/DEV-566
> Enable Leaders on MWRF

- sites/machinedesign.com/config/navigation.js
Per: https://southcomm.atlassian.net/browse/DEV-567
> Add “Company Directory” to site menu

- sites/mwrf.com/config/navigation.js
Per: https://southcomm.atlassian.net/browse/DEV-566
> Update site menu

- sites/bulktransporter.com/config/navigation.js
- sites/bulktransporter.com/config/site.js
- sites/contractingbusiness.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
- sites/fleetmaintenance.com/config/navigation.js
- sites/fleetmaintenance.com/config/site.js
- sites/fleetowner.com/config/navigation.js
- sites/fleetowner.com/config/site.js
- sites/refrigeratedtransporter.com/config/navigation.js
- sites/refrigeratedtransporter.com/config/site.js
- sites/trailer-bodybuilders.com/config/navigation.js
- sites/trailer-bodybuilders.com/config/site.js
- sites/trucker.com/config/navigation.js
- sites/trucker.com/config/site.js
Related nav update requests:
https://southcomm.atlassian.net/browse/DEV-601
https://southcomm.atlassian.net/browse/DEV-600
https://southcomm.atlassian.net/browse/DEV-541
https://southcomm.atlassian.net/browse/DEV-578
https://southcomm.atlassian.net/browse/DEV-572
Enable FM’s RMI: https://southcomm.atlassian.net/browse/DEV-581
> Assorted site menu updates

- sites/bulktransporter.com/config/navigation.js
- sites/ecmweb.com/config/navigation.js
- sites/refrigeratedtransporter.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-578
https://southcomm.atlassian.net/browse/DEV-600
> Couple additional site menu changes

- sites/sourcetoday.com/config/site.js
Re: https://southcomm.atlassian.net/browse/DEV-638
> Disable lazy loading

- sites/mhlnews.com/config/navigation.js
Request: https://southcomm.atlassian.net/browse/DEV-665
> Add ‘Podcasts’ to site menu

- sites/refrigeratedtransporter.com/config/dragon-forms.js
Modified the omedasite value from `RFTnewpref` to `RTnewpref` per https://southcomm.atlassian.net/browse/DEV-689
> Update dragonform URI

- sites/tdworld.com/config/navigation.js
Added “Executive Adivsory Board” per https://southcomm.atlassian.net/browse/DEV-671
> Update tdw site menu

- sites/machinedesign.com/config/site.js
Per https://southcomm.atlassian.net/browse/DEV-739
> Disable lazy load on MD

- sites/mhlnews.com/config/navigation.js
https://southcomm.atlassian.net/browse/DEV-769
> Nav menu updates

- sites/mhlnews.com/config/navigation.js
Updated White Papers & Podcasts to White Papers & eBooks
https://southcomm.atlassian.net/browse/DEV-933
> Updated nav
